/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IPerpEngine {
    function initializeProduction(
        address oracle,
        address vault,
        address multi_call_manager,
        uint256 mmr,
        bytes32 ticker_asset_currency,
        uint32 fee_frontend,
        uint32 fee_lp,
        address fee_protocol_addr,
        uint256 trading_fee,
        uint256 flat_trading_fee,
        uint256 ema_param
    )
        external;

    function trade(
        bool direction,
        uint256 size,
        uint256 min_trade_return,
        uint256 initial_guess,
        address frontend_address,
        uint8 leverage,
        bytes calldata unverified_report
    )
        external
        returns (uint256);

    function tradeFor(
        address user,
        bool direction,
        uint256 size,
        uint256 min_trade_return,
        uint256 initial_guess,
        address frontend_address,
        uint8 leverage,
        bytes calldata unverified_report
    )
        external
        returns (uint256);

    function closeAndWithdraw(
        uint256 max_slippage,
        uint256 max_liq_fee,
        address frontend_address,
        bytes calldata unverified_report
    )
        external;

    function closeAndWithdrawFor(
        address user,
        uint256 max_slippage,
        uint256 max_liq_fee,
        address frontend_address,
        bytes calldata unverified_report
    )
        external;

    function addLiquidity(
        uint256 liquidity_stable,
        uint256 liquidity_asset,
        uint256 max_fee_value,
        bytes calldata unverified_report
    )
        external;

    function addLiquidityFor(
        address user,
        uint256 liquidity_stable,
        uint256 liquidity_asset,
        uint256 max_fee_value,
        bytes calldata unverified_report
    )
        external;

    function removeLiquidity(
        uint256 liquidity_stable_to_remove,
        uint256 liquidity_asset_to_remove,
        uint256 max_fee_value,
        bytes calldata unverified_report
    )
        external;

    function removeLiquidityFor(
        address user,
        uint256 liquidity_stable_to_remove,
        uint256 liquidity_asset_to_remove,
        uint256 max_fee_value,
        bytes calldata unverified_report
    )
        external;

    function globalLiquidityStable() external view returns (uint256);

    function globalLiquidityAsset() external view returns (uint256);

    function liquidate(address user, uint256 liquidated_position_size, bytes calldata unverified_report) external;

    function liquidateFor(
        address liquidator,
        address user,
        uint256 liquidated_position_size,
        bytes calldata unverified_report
    )
        external;

    function realizePnL(bytes calldata unverified_report) external returns (uint256, bool);

    function realizePnLFor(address user, bytes calldata unverified_report) external returns (uint256, bool);

    function enableAutoClose(uint256 profit_th, uint256 loss_th, uint256 max_slippage, uint256 max_liq_fee) external;

    function enableAutoCloseFor(
        address user,
        uint256 profit_th,
        uint256 loss_th,
        uint256 max_slippage,
        uint256 max_liq_fee
    )
        external;

    function disableAutoClose() external;

    function disableAutoCloseFor(address user) external;

    function autoCloseUserPosition(address user, address frontend_address, bytes calldata unverified_report) external;

    function autoCloseUserPositionFor(
        address caller,
        address user,
        address frontend_address,
        bytes calldata unverified_report
    )
        external;

    function autoCloseUsersData(address user)
        external
        view
        returns (bool authorized, uint256 profitTh, uint256 lossTh, uint256 maxSlippage, uint256 maxLiqFee);

    function hasRole(bytes32 role, address account) external view returns (bool);

    function grantRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;

    function renounceRole(bytes32 role, address caller_confirmation) external;

    function setTrustedForwarder(address forwarder) external;

    function isTrustedForwarder(address forwarder) external view returns (bool);

    function updateFG(bytes calldata unverified_report) external;

    function prepareTimeLockedParameters(
        uint256 mmr,
        uint256 trading_fee,
        uint256 flat_trading_fee,
        uint256 fee_lp,
        uint256 liquidity_min_fee,
        uint256 liquidity_max_fee,
        uint256 liquidity_fee_k,
        uint256 funding_c,
        uint256 param_time_lock,
        uint256 minimum_trade_size
    )
        external;

    function setTimeLockedParameters(
        uint256 mmr,
        uint256 trading_fee,
        uint256 flat_trading_fee,
        uint256 fee_lp,
        uint256 liquidity_min_fee,
        uint256 liquidity_max_fee,
        uint256 liquidity_fee_k,
        uint256 funding_c,
        uint256 param_time_lock,
        uint256 minimum_trade_size
    )
        external;

    function setUnguardedParameters(
        address oracle,
        uint32 fee_frontend,
        address fee_protocol_addr,
        uint256 insurance_fund_cap,
        uint8 max_leverage,
        uint32 liquidation_discount,
        uint8 max_lp_leverage,
        uint8 slip_liquidation_th
    )
        external;

    function getLpLiquidityBalance(address user) external view returns (uint256, uint256);

    function getPrice() external view returns (uint256);

    function calcPnL(address user, uint256 price) external view returns (uint256, bool);

    function ReadParameters()
        external
        view
        returns (
            address,
            address,
            uint256,
            uint256,
            uint256,
            uint256,
            uint256,
            bytes32,
            uint256,
            bool,
            uint256,
            uint256,
            uint256,
            uint256,
            uint256,
            bool
        );

    function lastOperationTimestamp() external view returns (uint256);

    function MMR() external view returns (uint256);

    function maxLpLeverage() external view returns (uint256);

    function userVirtualTraderPosition(address user)
        external
        view
        returns (uint256, uint256, uint256, uint256, uint256, bool, uint256, bool);

    function liquidityPosition(address user) external view returns (uint256, uint256, uint256, uint256);

    function ReadFees()
        external
        view
        returns (uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, bool);

    function curveParameters()
        external
        view
        returns (uint256, uint256, uint256, uint256, uint256, uint256, bool, uint256);

    function computeFundingRate(uint256 price, uint256 timestamp) external view returns (uint256, bool);

    function _computeFundingFee(
        address user,
        uint256 funding_rate,
        bool funding_rate_sign
    )
        external
        view
        returns (uint256, bool);

    event ExecutedTrade(
        address indexed user,
        bool direction,
        uint256 tradeSize,
        uint256 tradeReturn,
        uint256 currentPrice,
        uint256 leverage
    );
    event ClosedPosition(address indexed user, uint256 pnl, bool pnlSign);
    event LiquidityMoved(
        address indexed user, uint256 liquidityStable, uint256 liquidityAsset, uint256 fee, bool added
    );
    event LiquidatedUser(
        address indexed user,
        address liquidator,
        uint256 fraction,
        uint256 liquidationFee,
        uint256 positionSize,
        uint256 currentPrice,
        int256 deltaPnl,
        bool liquidationDirection
    );
    event ToggledAutoClose(
        address indexed user, uint256 profitTh, uint256 lossTh, uint256 maxSlippage, uint256 maxLiqFee
    );
    event RealizedPnL(address indexed user, uint256 pnl, bool pnlSign);
    event ParametersUpdated(
        address _oracle,
        uint256 _feeFrontend,
        address _feeProtocolAddr,
        uint256 _insuranceFundCap,
        uint256 _maxLeverage,
        uint256 _liquidationDiscount
    );
    event LockedParameterUpdate(
        uint256 paramLockedUntil,
        uint256 _MMR,
        uint256 _tradingFee,
        uint256 _flatTradingFee,
        uint256 _feeLP,
        uint256 _liquidityMinFee,
        uint256 _liquidityMaxFee,
        uint256 _liquidityFeeK,
        uint256 _fundingC,
        uint256 _paramTimeLock,
        uint256 _minimumTradeSize
    );
    event TrustedForwarderUpdated(address indexed oldForwarder, address indexed newForwarder);
}
